
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

#make some changes
#make other changes
#why???
# awesome game
#take it easy

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x800")
window.configure(bg = "#6667AB")


canvas = Canvas(
    window,
    bg = "#6667AB",
    height = 800,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    365.0,
    400.0000000000002,
    image=image_image_1
)

canvas.create_rectangle(
    425.0,
    0.0,
    1200.0,
    800.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    483.0,
    162.0,
    anchor="nw",
    text="Welcome",
    fill="#64627C",
    font=("SackersGothicLightAT", 60 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    783.0,
    340.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#E8E8F2",
    highlightthickness=0,
    font=("SackersGothicLightAT", 30 * -1)
)
entry_1.place(
    x=503.0 + 10,
    y=260.0 + 80,
    width=560.0 - 10,
    height=158.0 - 80
)


canvas.create_text(
    510.0,
    298.0,
    anchor="nw",
    text="Enter Your Name",
    fill="#64627C",
    font=("SackersGothicLightAT", 30 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
NewGame = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("New Game clicked"),
    relief="flat"
)
NewGame.place(
    x=483.0,
    y=483.0,
    width=290.0,
    height=90.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
JoinGame = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Join Game clicked"),
    relief="flat"
)
JoinGame.place(
    x=483.0,
    y=620.0,
    width=290.0,
    height=90.0
)

canvas.create_text(
    65.0,
    321.0,
    anchor="nw",
    text="Use your knowledge to\ncompete with your\nfriends\nLearn for fun!",
    fill="#FFFFFF",
    font=("Montserrat Alternates", 16)
)

canvas.create_rectangle(
    65.0,
    279.0,
    285.0,
    286.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    65.0,
    157.0,
    anchor="nw",
    text="Online",
    fill="#FFFFFF",
    font=("Montserrat Alternates", 40 * -1)
)

canvas.create_text(
    65.0,
    206.0,
    anchor="nw",
    text="Quiz",
    fill="#FFFFFF",
    font=("Montserrat Alternates", 40 * -1)
)
window.resizable(False, False)
window.mainloop()
